### ISSUE TITLE
'CssAnimationSequencer' is already declared in the upper scope.

### ISSUE THREAD

**Issue by adius** [nickgravelyn/css-animation-sequencer#1]
Hi,
I used [Feram] to check your repo and found this issue:

"'CssAnimationSequencer' is already declared in the upper scope."

```diff
--- css-animation-sequencer.iife.js
+++ css-animation-sequencer.iife.js
@@ -26,1 +26,1 @@
   }
 
-  var CssAnimationSequencer = function CssAnimationSequencer () {  // FIXME //
     this._animations = []
   }

```

I hope it helps!

If you want to use it as well, it’s for free and really simple to integrate:
[feram.io/help/getting-started]

[Feram]: https://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

**Comment by nickgravelyn** [comment]
That file is generated by a tool. I also don’t believe this is an issue since ultimately the outer scope variable is assigned the inner variable’s value.
